sudo: required
services:
  - docker

before_install:
  - docker build -t invincible100/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -t invincible100/react-test npm run test -- --coverage

after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push invincible0305/multi-client
  - docker push invincible0305/multi-nginx
  - docker push invincible0305/multi-server
  - docker push invincible0305/multi-worker
